apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - echo "<html><body><h1>Homework Pod</h1></body></html>" > /init/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
  resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]